# Generated by Django 5.2.17 on 2026-09-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="check_in_lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="check_in_lng",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="check_out_lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="check_out_lng",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="distance_from_branch_meters",
            field=models.FloatField(
                blank=True,
                help_text="Distance from branch at check-in in meters",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="is_location_verified",
            field=models.BooleanField(
                default=False, help_text="True if verified within branch geofence"
            ),
        ),
    ]
