# Generated by Django 5.2.17 on 2026-09-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="geofence_enabled",
            field=models.BooleanField(
                default=True, help_text="Enforce strict location verification"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Branch Latitude",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Branch Longitude",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="radius_meters",
            field=models.PositiveIntegerField(
                default=200, help_text="Allowed geofence radius in meters"
            ),
        ),
    ]
